button:
  - platform: template
    name: "On"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xFF00
  - platform: template
    name: "Off"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xFD02
  - platform: template
    name: "2H"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xFB04
  - platform: template
    name: "4H"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xF906
  - platform: template
    name: "6H"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xF708
  - platform: template
    name: "8H"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xF50A
  - platform: template
    name: "CANDLE"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xF30C
  - platform: template
    name: "LIGHT"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xF10E
  - platform: template
    name: "Brightness -"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xEF10
  - platform: template
    name: "Brightness +"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xB708
          command: 0xED12
